/* THIS FILE IS AUTOGENERATED - DO NOT EDIT */

#ifndef DGOSPREY_REVISION_H
#define DGOSPREY_REVISION_H

<<<<<<< HEAD
#define DGOSPREY_REVISION "git commit 0d37e4d on 2017-08-25"
=======
<<<<<<< HEAD
#define DGOSPREY_REVISION "git commit be39ba4 on 2017-07-12"
#define DGOSPREY_VERSION "be39ba4"
=======
#define DGOSPREY_REVISION "git commit 8499a23 on 2017-08-25"
>>>>>>> 0d37e4dcbdc095294dcaa31b776789ce1f145b8d
>>>>>>> cd5ec83a1db6ffb8fdda6ffcfcf75f948d507e13

#endif // DGOSPREY_REVISION_H
